# Generated by Django 3.0.7 on 2020-06-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='audience',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='open_date',
            field=models.DateField(),
        ),
    ]
